name: ClangFormat Check

on: [push, pull_request]

jobs:
  clang-format:
    name: Run ClangFormat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ClangFormat
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check ClangFormat
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base_commit=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
            git diff --name-only $base_commit ${{ github.sha }} | grep -E '\.(cpp|h|c|cc|cxx|hpp)$' | xargs -r clang-format --style=file --dry-run --Werror
          else
            git diff --name-only HEAD^ HEAD | grep -E '\.(cpp|h|c|cc|cxx|hpp)$' | xargs -r clang-format --style=file --dry-run --Werror
          fi
